feat(assign-metrics): initial implementation of the assign-metrics policyt
gravitee-io/gravitee-policy-assign-metrics pull request #1
Opened 2021-01-08 16:30 UTC by phiz71

The file `src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker` is to be able to mock final classes
https://www.baeldung.com/mockito-final#configure-mocktio

Closes gravitee-io/issues#4769

2021-01-14 08:28 UTC, ytvnr requested changes
few remarks

2021-01-14 08:28 UTC, ytvnr commented on src/main/java/io/gravitee/policy/assignmetrics/AssignMetricsPolicy.java
> +            assignVariablePolicyConfiguration.getScope() == PolicyScope.REQUEST_CONTENT
```suggestion
     PolicyScope.REQUEST_CONTENT.equals(assignVariablePolicyConfiguration.getScope())
```

OR (as == with enum is null safe)

```suggestion
    assignVariablePolicyConfiguration.getScope() == PolicyScope.REQUEST_CONTENT
```

2021-01-14 08:28 UTC, ytvnr commented on src/main/java/io/gravitee/policy/assignmetrics/AssignMetricsPolicy.java
> +            assignVariablePolicyConfiguration.getScope() == PolicyScope.RESPONSE_CONTENT
```suggestion
            PolicyScope.RESPONSE_CONTENT.equals(assignVariablePolicyConfiguration.getScope())
```

OR (as == with enum is null safe)

```suggestion
    assignVariablePolicyConfiguration.getScope() == PolicyScope.RESPONSE_CONTENT
```

2021-01-14 08:28 UTC, ytvnr commented on src/main/java/io/gravitee/policy/assignmetrics/AssignMetricsPolicy.java
> +        }
Do you think it is possible to refactor since you do exactly the same for request ?

2021-01-14 08:28 UTC, ytvnr commented on src/main/java/io/gravitee/policy/assignmetrics/AssignMetricsPolicy.java
> +        if (assignVariablePolicyConfiguration.getScope() == null || assignVariablePolicyConfiguration.getScope() == PolicyScope.REQUEST) {
same remark for enum equality

2021-01-14 08:28 UTC, ytvnr commented on src/main/java/io/gravitee/policy/assignmetrics/AssignMetricsPolicy.java
> +        if (assignVariablePolicyConfiguration.getScope() != null && assignVariablePolicyConfiguration.getScope() == PolicyScope.RESPONSE) {
same for enum equality

2021-01-14 12:01 UTC, phiz71 commented on README.adoc
> +image:https://ci.gravitee.io/buildStatus/icon?job=gravitee-io/gravitee-policy-assign-metrics/master["Build status", link="https://ci.gravitee.io/buildStatus/icon?job=gravitee-io/gravitee-policy-assig
I think we can keep it. We will need to change every README when we use CircleCI

2021-01-14 12:24 UTC, phiz71 commented on src/main/java/io/gravitee/policy/assignmetrics/AssignMetricsPolicy.java
> +            assignVariablePolicyConfiguration.getScope() == PolicyScope.REQUEST_CONTENT
fix by 951af64

2021-01-14 12:24 UTC, phiz71 commented on src/main/java/io/gravitee/policy/assignmetrics/AssignMetricsPolicy.java
> +            assignVariablePolicyConfiguration.getScope() == PolicyScope.RESPONSE_CONTENT
fix by 951af64

2021-01-14 12:25 UTC, phiz71 commented on src/main/java/io/gravitee/policy/assignmetrics/AssignMetricsPolicy.java
> +        }
fix by 951af64

2021-01-14 12:25 UTC, phiz71 commented on src/main/java/io/gravitee/policy/assignmetrics/AssignMetricsPolicy.java
> +        if (assignVariablePolicyConfiguration.getScope() == null || assignVariablePolicyConfiguration.getScope() == PolicyScope.REQUEST) {
fix by 951af64

2021-01-14 12:25 UTC, phiz71 commented on src/main/java/io/gravitee/policy/assignmetrics/AssignMetricsPolicy.java
> +        if (assignVariablePolicyConfiguration.getScope() != null && assignVariablePolicyConfiguration.getScope() == PolicyScope.RESPONSE) {
fix by 951af64

2021-01-14 12:52 UTC, ytvnr approved these changes

2021-01-15 15:23 UTC, brasseld requested changes

2021-01-15 15:23 UTC, brasseld commented on README.adoc
> +You can use the `assign-metrics` policy to create custom metrics on your requests. These metrics can then be used in analytics dashboard to create custom table widget.
This policy enables you to push extended metrics than the one provided natively from request metrics. These metrics can then be used from analytics dashboards to create custom widget and, optionally, apply aggregations based on their value.

2021-01-15 15:23 UTC, brasseld commented on README.adoc
> +To be able to filter on a custom header, you can add this metric on your request flow.
This use-case is not really clear. Should probably be improved a bit.

2021-01-20 09:14 UTC, plsstephenson requested changes

2021-01-20 09:14 UTC, plsstephenson commented on README.adoc
> +This policy enables you to push extended metrics than the one provided natively from request metrics.
You can use the `assign-metrics` policy to push extra metrics in addition to the natively provided request metrics.

2021-01-20 09:14 UTC, plsstephenson commented on README.adoc
> +To display the distribution of your requests depending on an HTTP header in your dashboards, you can create this custom metric to catch the header of your requests.
To display your request distribution based on a particular HTTP header in your dashboards, create the custom metric shown below.

2021-02-01 20:19 UTC, merged